# Generated by Django 3.1.4 on 2020-12-11 20:18

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201211_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500), size=None),
        ),
    ]
