# Generated by Django 3.1.4 on 2020-12-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201211_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionImg',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
