# Generated by Django 3.1.4 on 2020-12-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
