# Generated by Django 3.1.4 on 2020-12-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название группы')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('questions', models.ManyToManyField(related_name='questions', to='api.Question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Группа вопросов',
                'verbose_name_plural': 'Группы вопросов',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='difficult',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.difficultylevel', verbose_name='Уровень сложности'),
        ),
    ]
